import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

async function buildData() {
  const dataDir = join(ROOT, "data");
  const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json"));
  files.sort();

  function rgbaToHex8(rgba) {
    const m = rgba.match(
      /rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)/,
    );
    if (!m) return null;
    const [, r, g, b, a] = m;
    const hex = (n) => Number(n).toString(16).padStart(2, "0");
    return `#${hex(r)}${hex(g)}${hex(b)}${hex(Math.round(Number(a) * 255))}`;
  }

  const result = {};
  for (const file of files) {
    const key = file.replace(/\.json$/, "");
    const raw = JSON.parse(await readFile(join(dataDir, file), "utf-8"));
    const colors = { ...(raw.colors ?? raw) };
    if (raw.rawColors) {
      for (const [name, rgba] of Object.entries(raw.rawColors)) {
        const hex8 = rgbaToHex8(rgba);
        if (hex8) colors[name] = hex8;
      }
    }
    result[key] = colors;
  }

  const js =
    "// AUTO-GENERATED by `npm run build` from data/*.json — do not edit manually\n" +
    `const DATA = ${JSON.stringify(result, null, 2)};\n`;
  await writeFile(join(ROOT, "data.js"), js);
  console.log(`Built data.js (${files.length} files)`);
}

async function buildNotes() {
  const md = await readFile(join(ROOT, "notes.md"), "utf-8");
  const rawHtml = await marked.parse(md);

  const wrapped = rawHtml
    .replace(/(<h3[\s>])/g, "</section>\n<section>\n$1")
    .replace(/^<\/section>\n/, "")
    .concat("\n</section>");

  const START = "<!-- NOTES:START -->";
  const END = "<!-- NOTES:END -->";

  const indexPath = join(ROOT, "index.html");
  const html = await readFile(indexPath, "utf-8");

  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    console.error("Missing NOTES:START / NOTES:END markers in index.html");
    process.exit(1);
  }

  const before = html.substring(0, startIdx + START.length);
  const after = html.substring(endIdx);
  const result = before + "\n" + wrapped + "\n    " + after;

  await writeFile(indexPath, result);
  console.log("Built notes into index.html");
}

async function main() {
  await buildData();
  await buildNotes();
}

main();
